// ─── SHARED DATA (Klassen, Fächer, Klausuren, Ferien) ──────────────────────────
// Wird von stundenplan.html und klausurenplan.html eingebunden.

const CLASSES = [
  {id:'info1',  name:'Info 1',  room:'Raum 5'},
  {id:'info2',  name:'Info 2',  room:'Raum 1'},
  {id:'freko1', name:'Freko 1', room:'Raum 4'},
  {id:'freko2', name:'Freko 2', room:'Raum 2'},
  {id:'mr',     name:'MR',      room:'Raum 3'},
];

// {label, cls, display}
const SM = {
  JAVA:   {l:'Java',          c:'sc-java', d:'Java'},
  Linux:  {l:'Linux',         c:'sc-linux',d:'Linux'},
  Acc:    {l:'Access',        c:'sc-acc',  d:'Access'},
  BWL:    {l:'BWL',           c:'sc-bwl',  d:'BWL'},
  Rewe:   {l:'Rechnungswesen',c:'sc-rewe', d:'Rewe'},
  Orga:   {l:'Organisation',  c:'sc-orga', d:'Orga'},
  E:      {l:'Englisch',      c:'sc-e',    d:'Englisch'},
  Ma:     {l:'Mathematik',    c:'sc-ma',   d:'Mathe'},
  DVHard: {l:'DV Hardware',   c:'sc-dv',   d:'DV Hard'},
  DVNet:  {l:'DV Netzwerke',  c:'sc-dv',   d:'DV Netz'},
  DVServ: {l:'DV Server',     c:'sc-dv',   d:'DV Serv'},
  WEB:    {l:'Web-Entwicklung',c:'sc-web', d:'WEB'},
  PuG:    {l:'Politik & Ges.',c:'sc-pug',  d:'PuG'},
  Python: {l:'Python',        c:'sc-py',   d:'Python'},
  Exc:    {l:'Excel',         c:'sc-exc',  d:'Excel'},
  KI:     {l:'Künstl. Intell.',c:'sc-ki',  d:'KI'},
  KIProj: {l:'KI-Projekt',    c:'sc-ki',   d:'KI-Proj'},
  Wima:   {l:'Wirtschaftsmath.',c:'sc-wima',d:'WiMa'},
  InV:    {l:'Investition',   c:'sc-inv',  d:'InV'},
  Voc:    {l:'Vokabeln (E)',  c:'sc-voc',  d:'Voc'},
  SQL:    {l:'SQL',           c:'sc-sql',  d:'SQL'},
  OrgaP:  {l:'Orga-Projekt',  c:'sc-orga', d:'Orga Proj'},
  SGram:  {l:'S. Grammatik',  c:'sc-e',    d:'S. Gram'},
  SSpue:  {l:'Schreibübung',  c:'sc-voc',  d:'S. Spü'},
  Hako:   {l:'Handelskorr.',  c:'sc-orga', d:'Hako'},
  Ft:     {l:'Fachtext',      c:'sc-zzz',  d:'Fachtext'},
  Spue:   {l:'Schreibübung',  c:'sc-voc',  d:'Spü'},
  Gram:   {l:'Grammatik',     c:'sc-e',    d:'Gramm.'},
  Dic:    {l:'Diktat',        c:'sc-voc',  d:'Diktat'},
  Dol:    {l:'Dolmetschen',   c:'sc-e',    d:'Dolm.'},
  SUeber: {l:'S. Übersetzung',c:'sc-e',    d:'S. Über'},
  Hea:    {l:'Hör-/Leseverst.',c:'sc-e',   d:'Hea'},
  HeaU:   {l:'Hör-/Üb.',     c:'sc-e',    d:'Hea/Üb'},
  Hia:    {l:'Hör-/Einstieg', c:'sc-e',    d:'Hia'},
  Her:    {l:'Hör-/Einstieg', c:'sc-e',    d:'Her'},
  Ppt:    {l:'Präsentation',  c:'sc-exc',  d:'Präs.'},
  D:      {l:'Deutsch',       c:'sc-e',    d:'Deutsch'},
  SUe:    {l:'Schreibübung',  c:'sc-voc',  d:'S. Üb'},
  SGram2: {l:'S. Grammatik',  c:'sc-e',    d:'S. Gram'},
  SHako:  {l:'S. Handelskorr.',c:'sc-orga',d:'S. Hako'},
  SpueS:  {l:'Schreib-Übung', c:'sc-voc',  d:'Spü S'},
  Laku:   {l:'Lagerbuchhalt.',c:'sc-bwl',  d:'LaBu'},
  Hifa:   {l:'Hör-Fachtext',  c:'sc-zzz',  d:'Hifa'},
  Hefa:   {l:'Hör-Fachtext',  c:'sc-zzz',  d:'Hefa'},
  Ge:     {l:'Geschichte',    c:'sc-geo',  d:'Geschichte'},
  Sowe:   {l:'Sozialwirtsch.',c:'sc-sowe', d:'Sowe'},
  Phy:    {l:'Physik',        c:'sc-phy',  d:'Physik'},
  DFoe:   {l:'Dt. Förderung', c:'sc-e',    d:'D. Fö'},
  DGrund: {l:'Dt. Grundlagen',c:'sc-e',    d:'D. Grund'},
  MaFoe:  {l:'Ma-Förderung',  c:'sc-ma',   d:'Ma Fö'},
};
function sm(s){return SM[s]||{l:s,c:'sc-zzz',d:s}}

// Klausurtermine pro Klasse
const EXAMS = {
  info1:[
    {date:'2026-01-04',s:'Rewe',  l:'Rechnungswesen',t:'Klausur'},
    {date:'2026-01-05',s:'DVHard',l:'DV Netzwerke',  t:'Klausur'},
    {date:'2026-01-06',s:'Orga',  l:'Organisation',  t:'Klausur'},
    {date:'2026-01-13',s:'E',     l:'Englisch',       t:'Klausur'},
    {date:'2026-01-21',s:'BWL',   l:'BWL',            t:'Klausur'},
    {date:'2026-01-23',s:'Acc',   l:'Access',         t:'Klausur'},
    {date:'2026-01-26',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-01-30',s:'Ma',    l:'Mathematik',     t:'Klausur'},
    {date:'2026-03-10',s:'E',     l:'Englisch',       t:'Klausur'},
    {date:'2026-03-13',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-03-23',s:'DVHard',l:'DV Hardware',    t:'Klausur'},
    {date:'2026-03-27',s:'Ma',    l:'Mathematik',     t:'Klausur'},
    {date:'2026-04-13',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-04-15',s:'BWL',   l:'BWL',            t:'Klausur'},
    {date:'2026-04-22',s:'Exc',   l:'Excel',          t:'Klausur'},
    {date:'2026-04-23',s:'DVHard',l:'DV Hardware',    t:'Klausur'},
    {date:'2026-04-24',s:'Rewe',  l:'Rechnungswesen', t:'Klausur'},
    {date:'2026-04-28',s:'JAVA',  l:'Java',           t:'Klausur'},
    {date:'2026-04-29',s:'Orga',  l:'Organisation',   t:'Klausur'},
    {date:'2026-05-05',s:'E',     l:'Englisch',       t:'Klausur'},
    {date:'2026-05-07',s:'WEB',   l:'Webentwicklung', t:'Klausur'},
    {date:'2026-05-13',s:'Acc',   l:'Access',         t:'Klausur'},
    {date:'2026-05-18',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-05-21',s:'Python',l:'Python',         t:'Klausur'},
    {date:'2026-06-10',s:'Exc',   l:'Excel',          t:'Klausur'},
    {date:'2026-06-11',s:'KI',    l:'Künstl. Intell.',t:'Klausur'},
    {date:'2026-06-15',s:'BWL',   l:'BWL',            t:'Klausur'},
    {date:'2026-06-17',s:'Acc',   l:'Access',         t:'Klausur'},
    {date:'2026-06-18',s:'DVHard',l:'DV Hardware',    t:'Klausur'},
    {date:'2026-06-24',s:'Rewe',  l:'Rechnungswesen', t:'Klausur'},
    {date:'2026-06-26',s:'Ma',    l:'Mathematik',     t:'Klausur'},
    {date:'2026-06-29',s:'Orga',  l:'Organisation',   t:'Klausur'},
    {date:'2026-06-30',s:'JAVA',  l:'Java',           t:'Klausur'},
    {date:'2026-07-01',s:'Orga',  l:'AP Organisation',t:'AP'},
    {date:'2026-07-03',s:'WEB',   l:'AB Webentwicklung',t:'AP'},
    {date:'2026-07-06',s:'Python',l:'AP Python',      t:'AP'},
    {date:'2026-07-08',s:'SQL',   l:'AP SQL',         t:'AP'},
    {date:'2026-07-10',s:'E',     l:'Zeugnis 🎓',     t:'Zeugnis'},
  ],
  info2:[
    {date:'2026-01-02',s:'DVNet', l:'DV Netzwerke',   t:'Klausur'},
    {date:'2026-01-03',s:'BWL',   l:'BWL',            t:'Klausur'},
    {date:'2026-01-20',s:'Orga',  l:'Organisation',   t:'Klausur'},
    {date:'2026-01-27',s:'DVNet', l:'3D / Rewe',      t:'Klausur'},
    {date:'2026-01-28',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-01-29',s:'JAVA',  l:'Java',           t:'Klausur'},
    {date:'2026-02-02',s:'JAVA',  l:'AP Java',        t:'AP'},
    {date:'2026-02-04',s:'BWL',   l:'AB BWL',         t:'AP'},
    {date:'2026-02-06',s:'Rewe',  l:'AP Rewe',        t:'AP'},
    {date:'2026-03-16',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-04-16',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-04-20',s:'DVNet', l:'DV Netzwerke',   t:'Klausur'},
    {date:'2026-05-06',s:'KI',    l:'MS Project',     t:'Klausur'},
    {date:'2026-05-07',s:'WEB',   l:'Webentwicklung', t:'Klausur'},
    {date:'2026-05-12',s:'Linux', l:'Linux',          t:'Klausur'},
    {date:'2026-05-21',s:'Python',l:'Python',         t:'Klausur'},
    {date:'2026-05-22',s:'SQL',   l:'SQL',            t:'Klausur'},
    {date:'2026-06-08',s:'DVNet', l:'DV Netzwerke',   t:'Klausur'},
    {date:'2026-06-10',s:'Orga',  l:'Organisation',   t:'Klausur'},
    {date:'2026-06-12',s:'KI',    l:'KI',             t:'Klausur'},
    {date:'2026-06-23',s:'KI',    l:'MS Project',     t:'Klausur'},
    {date:'2026-07-10',s:'E',     l:'Zeugnis 🎓',     t:'Zeugnis'},
  ],
  freko1:null,
  freko2:null,
  mr:null,
};

const FERIEN = [
  {name:'Faschingsferien', s:'2026-02-16', e:'2026-02-20'},
  {name:'Osterferien',     s:'2026-03-30', e:'2026-04-11'},
  {name:'Pfingstferien',   s:'2026-05-30', e:'2026-06-13'},
  {name:'Sommerferien',    s:'2026-07-30', e:'2026-09-14'},
];
